### ISSUE TITLE
Train and test splits for the 2C dataset

### ISSUE THREAD

**Issue by anindita127** [Aman-Goel1/IMM#1]
Hi,

Very interesting work! Can you also release the code for the quantitative analysis used for getting the values in Tables 1,2 and 3 of the paper? Also, I would like to know which of the 44 motions in the 2C dataset are used in the model. Can you also mention the train and the test splits?

**Comment by Aman-Goel1** [comment]
Hi, for the split of 2C, please follow our paper. We take a randomized 3:1 Train to Test split on the 2C dataset after forward kinematics. The code to generate AFD is within the codebase itself. 

Thank you,
Aman
